server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp
dubbo:  scan:    basePackages: com.jt  application:    name: consumer-web  registry:    address: zookeeper://192.168.153.130:2182?backup=192.168.153.130:2181,192.168.153.130:2183
 

  